---
title: "Curriculum Vitae"
date: "1993-12-14"
---

<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>

# <i class='fa fa-file-pdf-o'></i> Fellipe Carvalho Gomes

<i class="fa fa-download"></i> Download da versão em pdf [aqui](https://www.dropbox.com/s/8ulv1m6jubdzf79/CV_Fellipe_Gomes.pdf?dl=0)

* <i class='fa fa-birthday-cake'></i>   14/12/1993 
* <i class='fa fa-whatsapp'></i>  (21) 99209-9067
* <i class='fa fa-google'></i>  <gomes.fellipe1@gmail.com>
* <i class='fa fa-github-alt'></i> [github.com/gomesfellipe](github.com/gomesfellipe)
* <i class='fa fa-linkedin-square'></i>   <https://www.linkedin.com/in/gomesfellipe/>
* <i class='fa fa-skype'></i>   <gomes.fellipe@hotmail.com>
* <i class='fa fa-align-justify'></i>   <http://lattes.cnpq.br/2860433689709342>
* <span class="iconify" data-icon="simple-icons:kaggle" data-inline="false"></span>  <https://www.kaggle.com/gomes555>
* <i class='fa fa-medium'></i>  <https://medium.com/@gomesfellipe>

## <span class="iconify" data-icon="bi:info-circle" data-inline="false"></span> Sobre mim

Apaixonado por dados e tecnologia, possuo experiência de mais de 5 anos de trabalho diário com linguagem R e Python para fins acadêmicos, profissionais e pessoais. Atividades práticas como coleta, preparação e análise automatizada de dados, visualizações profissionais, desenvolvimento de aplicações web e Dashboards, modelagem estatística, Machine Learning, Linux, banco de dados e mecanismos de busca fazem parte do meu dia a dia.

## <span class="iconify" data-icon="bytesize:work" data-inline="false"></span> Profissional

Atualmente atuo na área de Data Science na Accenture onde meu objetivo é aplicar conhecimentos de estatística e ciência de dados para desenvolvimento e implementação de modelos de Machine Learning para produção. 

## <span class="iconify" data-icon="grommet-icons:plan" data-inline="false"></span> Projetos/Planos

Formado em Estatística pela UFF e cursando MBA em Data Science na FGV, tenho participado de forma mais ativa no [Kaggle](https://www.kaggle.com/gomes555) (Kaggle Master) e faço cursos online constantemente tanto sobre minha área de atuação quanto sobre assuntos diversos como filosofia, desenvolvimento pessoal, empreendedorismo, performance, criatividade e inovação. Me considero um eterno aprendiz.

Minha intenção com este blog é poder compartilhar minha evolução e interagir com pessoas que se interessam pela Estatística e Ciência de Dados em geral. Também escrevo para a página Ensina.AI no Medium.

Me divirto e aprendo bastante com todos esses projetos! 

## <span class="iconify" data-icon="fluent:rocket-16-regular" data-inline="false"></span> Especialidades:

Programação em R e Python, Modelagem Estatística, Machine Learning, Análises Estatísticas, Text Mining, NLP, Automação, Visualizações, Desenvolvimento de aplicações Web e Dashboards (utilizando biblioteca Shiny) 

---

# <i class='fa fa-institution'></i> Formação Acadêmica
 	
* Curso de Graduação em Estatística– concluído em 2018 - UFF - Universidade Federal Fluminense
* MBA em Business Analytics e Big Data – concluído em 2021 - FGV - Fundação Getúlio Vargas

---

# <i class="fa fa-toggle-on"></i> Atual 

## <span class="iconify" data-icon="simple-icons:accenture" data-inline="false"></span> Cientista de Dados - Accenture   

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 09 / 2020 - até o momento (Tempo Integral)

* Gerenciar, arquitetar e analisar big data para construir insights baseados em dados e modelos de dados de alto impacto;
* Criar uma cadeia de valor para ajudar a enfrentar os desafios de adquirir dados, avaliar seu valor, destilar e analisar;
* Examinar dados de várias fontes e compartilhar percepções que fornecem vantagem competitiva. 

---

# <i class='fa fa-certificate'></i> Experiência Profissional

### <span class="iconify" data-icon="ic:twotone-science" data-inline="false"></span> Cientista de Dados - Laboratório de Inovação FGV IBRE 

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 05 / 2018 - 09 / 2020

* Análises estatísticas;
* Automação de relatórios em PDF para clientes externos com uso das linguagens de programação R, Latex, Markdown e disponibilizando o produto final em uma aplicação feita com Shiny;
* Criação de aplicativos (Shiny) para facilitar a análise exploratória e descritiva dos dados e uso de metodologias estatísticas para auxiliar a tomada de decisão;
* Apresentação de Workshop sobre construção de softwares para confecção de relatórios automáticos para entregas mensais;
* Manutenção e auxílio no desenvolvimento de streaming de Crawlers/Scrapers de dados na web;
* Análise de dados e aplicação de modelos de aprendizado de máquina e métodos estatísticos.

### <span class="iconify" data-icon="ic:twotone-science" data-inline="false"></span> Cientista de Dados - Model Thinking Br

####  <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 09 / 2019 - 10 / 2020

* Estruturação de documentos de texto (dados não estruturados);
* Análise dos dados aplicando técnicas de Text Mining e Machine Learning com as linguagens de programação R e Python;
* Processamento de Linguagem Natural;
* Modelagem Estatística e Machine Learning;
* Elaboração de um modelo heurísico para resolução do problema de negócio.

## <i class='fa fa-binoculars'></i> Freelancer como consultor

Ajuda à pesquisadores com trabalhos acadêmicos aplicando a metodologia estatística apropriada em cada projeto auxiliando na apresentação e interpretação de resultados obtidos.

###  AUXÍLIO COM ANÁLISES ESTATÍSTICAS PARA PESQUISADORA DA UFRJ

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 09 / 2017 - 10 / 2017

* Esclarecimento de duvidas, suporte na elaboração do relatório final e atendimento a solicitações do estudo de título: “Qualidade de vida de mulheres acometidas por câncer de mama localmente avançado” realizado na Escola de Enfermagem Anna Nery - UFRJ para o Programa de Pós-Graduação do Curso de Mestrado em Enfermagem
* Suporte no estabelecimento de métodos de análise, aplicação da metodologia apropriada e auxílio na interpretação dos resultados
* Cálculos de medidas estatísticas descritivas, construção de tabelas e gráficos para descrição e interpretação dos dados.

### AUXÍLIO COM ANÁLISES ESTATÍSTICAS PARA PESQUISADORA DA UFRJ

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 10 / 2017 - 11 / 2017

* Esclarecimento de duvidas, suporte na elaboração do relatório final e atendimento a solicitações do estudo de título: “Contato pele a pele entre recém-nascidos de baixo peso e os pais na unidade neonatal: um estudo observacional” realizado na Escola de Enfermagem Anna Nery - UFRJ
* Limpeza e estruturação do banco de dados
* Auxílio no estabelecimento de métodos de análises, em cálculos de medidas estatísticas descritivas, construção de tabelas e gráficos para descrição e interpretação dos dados

---

## <i class='graduation-cap'></i> PROJETOS E CARGOS DURANTE A GRADUAÇÃO EM ESTATÍSTICA NA UNIVERSIDADE FEDERAL FLUMINENSE - UFF

### INICIAÇÃO CIENTÍFICA - UFF

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 09 / 2017 - 06 / 2018

* Estudo orientado sobre a modelagem hierárquica bayesiana
* Trabalho com dados simulados com objetivo de analisar a sensibilidade da distribuição a priori escolhida e estudando sobre como inferir sobre os parâmetros desconhecidos
* Reuniões semanais com a docente para fazer apresentações sobre o conteúdo estudado, tirar dúvidas e mostrar os resultados obtidos  
* Repositório do projeto pode sr conferido [neste link](https://github.com/gomesfellipe/projeto_modelos_hierarquicos_bayesianos) no github

### DATAPREV - RJ - Estagiário

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 05 / 2017 - 05 / 2018

* Auxilío na conferência e confecção de tabelas gráficos e estatísticas descritivas para a publicação dos anuários (AEPS 2017 e AET 2017) com o uso dos softwares Excel e SAS Guide.
* Auxílio em projetos voltados ao monitoramento de redes sociais testando diferentes abordagens de análises descritivas e exploratórias com ferramentas de text mining além da elaboração do dashboard para a entrega dos resultados.
* Criação de um aplicativo para geração de Nuvem de Palavras com o uso do software R
* Auxílio na análise dos resultados de Pesquisa de Satisfação, com a elaboração de códigos em R para tratamento dos dados e aplicações de algorítimos de machine learning utilizando o R.

### Trabalho voluntário para pesquisadora da UFRJ

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 05 / 2017 – 08 / 2016

* Auxílio em análises, cálculos de estatísticas descritivas, confecção de gráficos e tabelas para publicação do artigo com o título de: “ Conhecimento dos estudantes de graduação em enfermagem sobre dor ” originado de um projeto em Enfermagem da Universidade Federal do Rio de Janeiro (UFRJ) – RJ.
* Definição de métodos de análise, aplicação da metodologia apropriada e interpretação dos resultados
* Suporte à pesquisadora com esclarecimento de dúvidas e atendimento a novas solicitações.


### Universidade Federal Fluminense - Monitor na disciplina Métodos Computacionais.

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 02 / 2016 – 12 / 2016

* Elaboração de métodos para resoluções de problemas estatísticos utilizando o ambiente R, confeccionar listas com gabaritos e resoluções dos exercícios do professor.
* Suporte às aulas práticas e auxilio em horários alternativos com aulas de duvidas.
 
[Certificado](https://www.dropbox.com/s/8dh4i3yjbrdgvn5/CertificadosMonitoriaMonitores2017_1494362616686.pdf?dl=0) 
 
### Universidade Federal Fluminense - Iniciação Científica

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 02 / 2016 – 12 / 2016

* Auxílio em análises de estatísticas descritivas e confecção de gráficos para relatório de dissertação de mestrado apresentado ao programa de pósgraduação e pesquisa em enfermagem, da Escola de Enfermagem Anna Nery da Universidade Federal Fluminense do Rio de Janeiro, com título de: "Amamentação, leite materno, e contato pele a pele no alívio da dor em recém nascidos submetidos à punção de calcâneo no alojamento conjunto".
   
### Universidade Federal Fluminense - Monitor de laboratório com sistema Linux

#### <span class="iconify" data-icon="clarity:date-line" data-inline="false"></span> 02 / 2015 - 12 / 2015

* Auxilio aos usuários do laboratório na utilização de Softwares Livres como Linux, disponível no laboratório, atendendo as demandas especificas de Softwares para o ensino e pesquisa.
* Colaboração em difundir o uso dos sistemas da universidade à comunidade acadêmica.

--- 
 
# <i class="fa fa-refresh fa-spin"></i> Habilidades 

* Microsoft Office (Word, Power Point e Excel)
* Programação em R 
* Programação em Python
* Linguagem <span class="latex">LaTeX</span> e Markdown
* SPSS
* Básico de CSS e HTML
* Desenvolvimento de aplicações web e dashboards com biblioteca Shiny

---

# <i class="fa fa-paperclip"></i> Certificados

Cursos de Verão:
   
   * [Curso de Verão 2018 - UFRJ: Introdução à Probabilidade](https://www.dropbox.com/preview/Certificados/Certificado%20UFRJ%20Curso%20de%20Verao%20Probabilidade.pdf)
   * [Curso de Verão 2019 - FGV: Introdução à Análise Real na Reta](https://www.dropbox.com/preview/Certificados/Certificado%20UFRJ%20Curso%20de%20Verao%20Probabilidade.pdf)
   * [Curso de Verão 2020 - FGV: Introdução à Análise Real na Reta](https://www.dropbox.com/preview/Certificados/Certificado%20UFRJ%20Curso%20de%20Verao%20Probabilidade.pdf)

   
[Curso-R](https://www.curso-r.com/cursos/):

   * [XGBoost](https://www.dropbox.com/s/pb9ayzhskj25him/Captura%20de%20Tela%202020-05-16%20%C3%A0s%2020.16.18.png?dl=0)
   * [Workshop - Deploy R em produção](https://www.dropbox.com/s/460h1nr67q5fjyw/Captura%20de%20Tela%202020-06-22%20%C3%A0s%2017.47.07.png?dl=0)
   * [Introdução ao R com C++](https://www.dropbox.com/s/f2r40ewmst2c2i0/Certificado%20curso%20RCPP.png?dl=0)
   * [Deep Learning](https://www.dropbox.com/s/cubloe585jf3c2d/certificado%20deep%20learning%20curso%20r.png?dl=0)
   
DataScienceAcademy:

   * [Programa de mentoria em Data Science](https://www.dropbox.com/s/url9hgx2d785hzs/Certificado%20Mentorado%20Fellipe%20Carvalho%20Gomes.pdf?dl=0)
   * [Formação Cientista de dados](https://www.dropbox.com/s/73uafvq71nglnw4/Certificado%20FCD%20Fellipe%20Carvalho%20Gomes.pdf?dl=0) 
      * [Big Data Analytics com R e Microsoft Azure Machine Learning](https://www.dropbox.com/s/rngqhg668m02dbn/certificate-big-data-analytics-com-r-e-microsoft-azure-machine-learning-57b1584047d7dd80cc8b4570.pdf?dl=0)
      * [Business Analytics](https://www.dropbox.com/s/48ofdzdj2xhonqa/certificate-business-analytics-58e9969d5e4cde52038b4570.pdf?dl=0)
      * [Visualização de dados e design de Dashboards](https://www.dropbox.com/s/rd61kwbu4fo2ae6/certificate-visualizacao-de-dados-e-design-de-dashboards-58e709435e4cdefbe18b4572.pdf?dl=0)
      * [Engenharia de Dados com Hadoop e Spark](https://www.dropbox.com/s/0fay6mc5acv98hy/certificate-engenharia-de-dados-com-hadoop-e-spark-57faebb047d7dd0b478b4574.pdf?dl=0)
      * [Big Data real time analytics com Python e Spark](https://www.dropbox.com/s/0czj5qddk5fqoyc/certificate-big-data-real-time-analytics-com-python-e-spark-57e4c3bd47d7dd281c8b4568.pdf?dl=0)
      * [Machine Learning](https://www.dropbox.com/s/t3ijls1lq55nth9/certificate-machine-learning-588c218f5e4cdee0af8b456d.pdf?dl=0)
      * [Big Data Analytics com R e Microsoft Azure Machine Learning](https://www.dropbox.com/s/rngqhg668m02dbn/certificate-big-data-analytics-com-r-e-microsoft-azure-machine-learning-57b1584047d7dd80cc8b4570.pdf?dl=0)
   
DataCamp:

   * [Kaggle Python Tutorial on Machine Learning Course](https://www.datacamp.com/statement-of-accomplishment/course/66df173370104b92f62ff831fa43e8415d32a465)
   * [Intro Python for Data Science Cource](https://www.dropbox.com/s/h9mhc9krk1589ue/Statement%20of%20Accomplishment%20-%20Kaggle%20Python%20Tutorial%20on%20Machine%20Learning%20Course.pdf?dl=0)
   * [Data Analysis in R, the data.table Way Course](https://www.dropbox.com/s/6lb8dt3tkv20fib/Statement%20of%20Accomplishment%20-%20Data%20Analysis%20in%20R%2C%20the%20data.table%20Way%20Course.pdf?dl=0)
   * [Machine Learning with Tree-Based Models in R](https://www.dropbox.com/s/bx6nuajd0txf5zd/Statement%20of%20Accomplishment%20-%20Machine%20Learning%20with%20Tree-Based%20Models%20in%20R.pdf?dl=0)
   * [Correlation and Regression Course]()
   * [Machine Learning in the Tidyverse](https://www.dropbox.com/s/tr9zipnnwz3l0tn/Statement%20of%20Accomplishment%20-%20Machine%20Learning%20in%20the%20Tidyverse.pdf?dl=0)
   * [Time Series with R - SKILL TRACK](https://www.datacamp.com/statement-of-accomplishment/track/a9f5e59b4440afcfd23a1ad0b6712a8d30418486) (6 cursos:)
      * [Manipulating Time Series Data in R with xts & zoo](https://www.dropbox.com/s/minbubg2dag6kn5/Statement%20of%20Accomplishment%20-%20Manipulating%20Time%20Series%20Data%20in%20R%20with%20xts%20%26%20zoo.pdf?dl=0)
      * [Introduction to Time Series Analysis Course](https://www.dropbox.com/s/hg7hbw2793c7vyq/Statement%20of%20Accomplishment%20-%20Introduction%20to%20Time%20Series%20Analysis%20Course.pdf?dl=0)
      * [ARIMA Modeling with R Course](https://www.dropbox.com/s/y6zp9mgmt0khlpc/Statement%20of%20Accomplishment%20-%20ARIMA%20Modeling%20with%20R%20Course.pdf?dl=0)
      * [Forecasting Using R](https://www.datacamp.com/statement-of-accomplishment/course/4eaee3ad1c179377e59b1c7b5e115bbf2a85efb4)
      * [Visualizing Time Series Data in R](https://www.datacamp.com/statement-of-accomplishment/course/c4b05ad717d26c6c3827f2f862ea262503866e3f)
      * [Manipulating Time Series Data in R: Case
Studies](https://www.datacamp.com/statement-of-accomplishment/course/86679df81182605a320ef4d4a766ef8573fe7cf9)

Seminários/Minicursos:

   * [Agenda Acadêmica 2014 - VI Semana da Estatística- SEMEST UFF](https://www.dropbox.com/s/asjb9duxjdxghtr/semest%202014.pdf?dl=0)
   * [Agenda Acadêmica 2015 - VII Semana da Estatística - SEMEST UFF](https://www.dropbox.com/s/j94jljwczoa0ofa/semest%202015.pdf?dl=0)
   * [Minicurso SER II - Desenvolvimento de Dashboards interativos com o R](https://www.dropbox.com/s/beih8kr1h1th5uy/Certificado%20SER%20II.pdf?dl=0)
   * [SER II: Seminário Internacional de Estatística com R](https://www.dropbox.com/s/f0flm3mevnt6qm9/SER%202016.pdf?dl=0)
   * [Workshop BI MASTER - PUC](https://www.dropbox.com/s/9ocxw4tmm6s7udm/FELIPE%20CARVALHO%20-%20BI%20MASTER%202017.pdf?dl=0)
   * [Minicurso SER III - Modelos de Regressão Linear Politômicos](https://www.dropbox.com/s/lyo93zpltq9k2qj/Certificado%20SER%20III%20-%20minicurso%20Modelos%20de%20Regressao%20Politomicos.pdf?dl=0)
   * [Minicurso SER III - Web Scraping utilizando o pacote Rvest](https://www.dropbox.com/s/9u0rtj6uayxc18n/Certificado%20SER%20III%20-%20minicurso%20Web%20Scraping.pdf?dl=0)
   * [SER III Seminário Internacional de Estatística com R](https://www.dropbox.com/s/fdo3namqkmuy51j/Certificado%20SER%20III.pdf?dl=0)
   * [SER IV Seminário Internacional de Estatística com R](https://www.dropbox.com/s/ap5hr6q5hdlx75m/Certificado%20SER%20IV%20Fellipe%20Carvalho%20Gomes.pdf?dl=0)

Udemy:

   * [Análise Exploratória de Dados - Udemy](https://www.udemy.com/certificate/UC-2HR7P4JI/)
   * [Visualização de Dados e Dashboards: Boas Práticas - Udemy](https://www.udemy.com/certificate/UC-G1KTLZXL/)
   * [Criando Páginas Web com o GitHub Pages - Udemy](https://www.udemy.com/certificate/UC-CNH02APP/?utm_campaign=email&utm_source=sendgrid.com&utm_medium=email)
   * [Formação Cientista de Dados - Udemy](https://www.udemy.com/certificate/UC-OCF4FMC6/)
   * [Super Formação Inteligência Artificial e Machine Learning - Udemy](https://www.udemy.com/certificate/UC-UREKLP27/)
   
Apresentações:

* [Ciência de Dados - Uma Visão Geral](https://www.dropbox.com/s/svm5zwgzkkvadu8/certificado-apresentacao-o-que-e-ciencia-de-dados-ias-uff.pdf?dl=0)

Cursos Gerais:

* [Splunk 7.x Fundamentals Part 1 (IOD)](https://www.dropbox.com/s/ad2n1b1zx1kaon5/splunk_1.pdf?dl=0)
* [Splunk 7.x Fundamentals Part 2 (IOD)](https://www.dropbox.com/s/0u3qp8bifhtznbb/splunk_2.pdf?dl=0)
   
Desenvolvimento Pessoal:

   * [Inteligência Emocional - Conquer](https://www.dropbox.com/s/y9dttdfkdzn2yk0/conquer_inteligencia_emocional.pdf?dl=0)
   * [Reaprendizagem Criativa - Keep Learning School](https://www.dropbox.com/s/r2vin6k2imrn71q/Re-aprendizagem%20Criativa%20-%20Keep%20Learning.pdf?dl=0)
   * [Técnicas de criatividade - Keep Learning School](https://www.dropbox.com/s/911tcwkjntl4ptb/tecnicas-de-criatividade-murilo-gun.pdf?dl=0)
   * [Curso de Meditação Método DeRose]()
   

 


<i class="fa fa-download"></i> Download da versão em pdf [aqui](https://www.dropbox.com/s/8ulv1m6jubdzf79/CV_Fellipe_Gomes.pdf?dl=0)


